export const expectedValue = [
  {
    empId: '9876',
    firstName: 'Nithiya',
    lastName: 'Mani',
    email: 'nithiya@gmail.com',
    mobile: 9876543210,
    address: 'xxxxxx',
  },
  {
    empId: '9874',
    firstName: 'Kavitha',
    lastName: 'Ravi',
    email: 'kavi@gmail.com',
    mobile: 6383800828,
    address: 'ndkncljcpq',
  },
  {
    empId: '1234',
    firstName: 'Sanjitha',
    lastName: 'Siva',
    email: 'sanju@gmail.com',
    mobile: 8769543210,
    address: 'Southkorea',
  },
  {
    empId: '8765',
    firstName: 'Kavyaji',
    lastName: 'Mohanraj',
    email: 'kavya@gmail.com',
    mobile: 6789054321,
    address: 'Coimbatore',
  },
  {
    empId: '1997',
    firstName: 'Kookie',
    lastName: 'Joen',
    email: 'btsjk@gmail.com',
    mobile: 6383638047,
    address: 'SouthKorea',
  },
  {
    empId: '9876',
    firstName: 'Nithiya',
    lastName: 'Mani',
    email: 'nithiya@gmail.com',
    mobile: 9876543210,
    address: 'xxxxxx',
  },
  {
    empId: '9874',
    firstName: 'Kavitha',
    lastName: 'Ravi',
    email: 'kavi@gmail.com',
    mobile: 6383800828,
    address: 'ndkncljcpq',
  },
  {
    empId: '1234',
    firstName: 'Sanjitha',
    lastName: 'Siva',
    email: 'sanju@gmail.com',
    mobile: 8769543210,
    address: 'Southkorea',
  },
  {
    empId: '8765',
    firstName: 'Kavyaji',
    lastName: 'Mohanraj',
    email: 'kavya@gmail.com',
    mobile: 6789054321,
    address: 'Coimbatore',
  },
  {
    empId: '1997',
    firstName: 'Kookie',
    lastName: 'Joen',
    email: 'btsjk@gmail.com',
    mobile: 6383638047,
    address: 'SouthKorea',
  },
  {
    empId: '9876',
    firstName: 'Nithiya',
    lastName: 'Mani',
    email: 'nithiya@gmail.com',
    mobile: 9876543210,
    address: 'xxxxxx',
  },
  {
    empId: '9874',
    firstName: 'Kavitha',
    lastName: 'Ravi',
    email: 'kavi@gmail.com',
    mobile: 6383800828,
    address: 'ndkncljcpq',
  },
  {
    empId: '1234',
    firstName: 'Sanjitha',
    lastName: 'Siva',
    email: 'sanju@gmail.com',
    mobile: 8769543210,
    address: 'Southkorea',
  },
  {
    empId: '8765',
    firstName: 'Kavyaji',
    lastName: 'Mohanraj',
    email: 'kavya@gmail.com',
    mobile: 6789054321,
    address: 'Coimbatore',
  },
  {
    empId: '1997',
    firstName: 'Kookie',
    lastName: 'Joen',
    email: 'btsjk@gmail.com',
    mobile: 6383638047,
    address: 'SouthKorea',
  },
];

export const expectedValue1 = [
  {
    empId: '9876',
    firstName: 'Nithiya',
    lastName: 'Mani',
    email: 'nithiya@gmail.com',
    mobile: 9876543210,
    address: 'xxxxxx',
    subtasks: [
      {
        firstName: 'Nithiya',
        lastName: 'Mani',
        email: 'nithiya@gmail.com',
        mobile: 9876543210,
        address: 'xxxxxx',
      },
    ],
  },
  {
    empId: '9874',
    firstName: 'Kavitha',
    lastName: 'Ravi',
    email: 'kavi@gmail.com',
    mobile: 6383800828,
    address: 'ndkncljcpq',
    subtasks: [
      {
        firstName: 'Kavitha',
        lastName: 'Ravi',
        email: 'kavi@gmail.com',
        mobile: 6383800828,
        address: 'ndkncljcpq',
      },
    ],
  },
  {
    empId: '1234',
    firstName: 'Sanjitha',
    lastName: 'Siva',
    email: 'sanju@gmail.com',
    mobile: 8769543210,
    address: 'Southkorea',
    subtasks: [
      {
        mark: 10,
      },
    ],
  },
  {
    empId: '8765',
    firstName: 'Kavyaji',
    lastName: 'Mohanraj',
    email: 'kavya@gmail.com',
    mobile: 6789054321,
    address: 'Coimbatore',
    subtasks: [
      {
        mark: 10,
      },
    ],
  },
  {
    empId: '1997',
    firstName: 'Kookie',
    lastName: 'Joen',
    email: 'btsjk@gmail.com',
    mobile: 6383638047,
    address: 'SouthKorea',
    subtasks: [
      {
        mark: 10,
      },
    ],
  },
  {
    empId: '9876',
    firstName: 'Nithiya',
    lastName: 'Mani',
    email: 'nithiya@gmail.com',
    mobile: 9876543210,
    address: 'xxxxxx',
    subtasks: [
      {
        mark: 10,
      },
    ],
  },
  {
    empId: '9874',
    firstName: 'Kavitha',
    lastName: 'Ravi',
    email: 'kavi@gmail.com',
    mobile: 6383800828,
    address: 'ndkncljcpq',
    subtasks: [
      {
        mark: 10,
      },
    ],
  },
  {
    empId: '1997',
    firstName: 'Kookie',
    lastName: 'Joen',
    email: 'btsjk@gmail.com',
    mobile: 6383638047,
    address: 'SouthKorea',
    subtasks: [
      {
        mark: 10,
      },
    ],
  },
];
